services:
    _defaults:
        autowire: true
        autoconfigure: true

    Keyboardman\FilesystemBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
